### ISSUE TITLE
Setting root folder problem (Windows)

### ISSUE THREAD

**Issue by purell** [stewarttylerr/ftp-srv#8] opened 2017-04-27 17:48 UTC
Hi,

I'm having problem setting the ftp root folder on Windows. Here is what I did : 

```
const ftp_srv = require('ftp-srv');
const f = new ftp_srv("127.0.0.1:21", {});
f.on('login', ({ username, password }, resolveLogin, rejectLogin) => {
return resolveLogin({
                root: "d:\\ftp_root",
                cwd: "/"
            });
)};
f.listen();
```

When the client is getting the file (LIST) the here is what I'm getting in `fs.js`
```
class FileSystem {
  constructor(connection, {
    root = '/',
    cwd = '/'
  } = {}) {
    this.connection = connection;
    this.cwd = nodePath.resolve(cwd);              // "/" = "d:/"
    this.root = nodePath.resolve(root);            // "d:\\ftp_root" = "d:\ftp_root"
  }
```

Now in the `list` function :
``` 
  list(path = '.') {
    path = this._resolvePath(path);                // path = "d:\ftp_rootd:\"
    return fs.readdir(path)
    .then(fileNames => {
```

Thus, `d:\ftp_rootd:\` is not a valid folder on my host. Why the `cmd` and the `root` folder are merge together ? Why not use only the `root` argument ?

**Comment by purell** [comment] 2017-04-27 19:18
To get thing working I had to do this in `fs.js` : 
```
const _ = require('lodash');
const nodePath = require('path');
const url = require('url');                                    // HERE
const uuid = require('uuid');
const when = require('when');
const whenNode = require('when/node');
const syncFs = require('fs');
const fs = whenNode.liftAll(syncFs);
const errors = require('./errors');

const isWin = /^win/.test(process.platform);

class FileSystem {
  constructor(connection, {
    root = '/',
    cwd = '/'
  } = {}) {
    this.connection = connection;
    this.cwd = nodePath.resolve(cwd);
    if (isWin) {                                                // HERE
      this.cwd = url.parse(this.cwd).path;
    }
    this.root = nodePath.resolve(root);
  }

  _resolvePath(path) {
    let pathParts = {                                           // HERE
      root: this.root,
      base: nodePath.resolve(this.cwd, path)
    };
    if (isWin) {                                                // HERE
      pathParts.base = url.parse(pathParts.base).path;
    }
    path = nodePath.format(pathParts);
    return path;
  }
```
But I'm not sure of this fix, maybe its will break something else...

**Comment by stewarttylerr** [comment] 2017-04-28 16:18
I'm leaning more towards serving a different file system if on windows rather than amending the current one (which was designed for unix based systems) to work.

The `login` event can resolve with a file system (https://github.com/stewarttylerr/ftp-srv/blob/master/src/connection.js#L60), which could be a windows based one. This could solve issues for now until a solution is determined.

**Comment by purell** [comment] 2017-04-28 16:51
Hi Stewart,

I'm agree with you that creating a new file system specific to Windows would be ideal. You could create it by copying the unix one but just replace the detect lines...

I doubt the https://github.com/stewarttylerr/ftp-srv/blob/master/src/connection.js#L60 fix will the problem as when calling `new FileSystem(this, {root, cwd})` the `cmd` value will still be overwrite by https://github.com/stewarttylerr/ftp-srv/blob/master/src/fs.js#L21 : 

```
const pathParts = {
      root: this.root,
      base: nodePath.resolve(this.cwd, path)
    };
```

// Setting cwd to '/' on Windows will be resolved as "X:\" and we get the same problem :(

**Comment by stewarttylerr** [comment] 2017-05-04 23:26
So it appears that node supports forward slashes (`/`) in paths on Windows.
Can you try using all forward slashes?
```
{
  root: "d:/ftp_root",
  cwd: "/"
}
```

Let me know if that works.

**Comment by purell** [comment] 2017-05-05 13:57
Nope, it does not work. `/` is resolve to `d:\` by the function path.resolve of FileSystem. I tried everything, `/` or `\` but the driver letter is always returns. It make sens as on Linux `/` will return `/` but on Windows `/` cannot returns `/` it should returns a driver letter at least.

![image](https://cloud.githubusercontent.com/assets/7946730/25748390/df4eda46-3178-11e7-9d5f-b5cfa6a3e626.png)

![image](https://cloud.githubusercontent.com/assets/7946730/25748385/db683d78-3178-11e7-8cab-cf9bae91249d.png)

So, `cwd` is `/`, when pass through `nodePath.resolve` it is transformed to `d:\` instead of `/`.

**Comment by stewarttylerr** [comment] 2017-05-05 16:52
Yeah the `resolve` function seems to be the issue.
I'm working on fixing it in this PR: https://github.com/stewarttylerr/ftp-srv/pull/12
Just need to setup a windows machine to test it!

**Comment by purell** [comment] 2017-05-05 18:06
Thank you so much Stewart, I appreciate it :)

**Comment by stewarttylerr** [comment] 2017-05-05 20:55
Testing this on windows VM:
```
{
  root: 'C:\users\User',
  cwd: '\'
}
```

Looks like it works in the new PR. Are you able to confirm this @purell?

One issue with FileZilla, it doesn't wrap requests in quotes so folder names with spaces do not work.

**Comment by stewarttylerr** [comment] 2017-05-06 00:29
Okay this is fixed with https://github.com/stewarttylerr/ftp-srv/pull/12!

**Closed by stewarttylerr** 2017-05-06 00:29 UTC

**Comment by purell** [comment] 2017-05-12 15:50
Wow, thank you so much Stewart, now it seems to work perfectly :)
